### ISSUE TITLE
image bug

### ISSUE THREAD

**Issue by mohamed-moanis** [mohamed-moanis/gotcha#15]
I can't take an image for a new device, nor I can retake an image
the camera application of the mobile is opened correctly, then everything goes black
till I return to the previous activity

**Comment by IbrahimHussiny** [comment]
it is working with me :( , maybe you have wrong files.

**Comment by IbrahimHussiny** [comment]
can you search for it ? as i can't tell what is problem exactly because it is working with me

**Comment by mohamed-moanis** [comment]
Its working for your version of android and your mobile only
thats not a working state

revise your code and test on different devices as you can

**Comment by IbrahimHussiny** [comment]
ok , i will see it

**Comment by mohamed-moanis** [comment]
now the take image is working correctly
but the retake image crashes
here is the stack trace : http://pastebin.com/Mu0d6pGx
