### ISSUE TITLE
enableWifi() class ClientManager

### ISSUE THREAD

**Issue by IbrahimHussiny** [mohamed-moanis/gotcha#22]
terminates the program-me on my device

**Comment by mohamed-moanis** [comment]
so....

**Comment by IbrahimHussiny** [comment]
http://pastebin.com/bNdmS0vi

**Comment by mohamed-moanis** [comment]
please synchronize your repository with master
as you can see from the log, its a lack of permission exception
you need to add the
```java
android.permission.ACCESS_WIFI_STATE
```
